obj-$(CONFIG_TOUCHSCREEN_HYN_CST3640) += hyn_cst3640_ts.o

hyn_cst3640_ts-y := hyn_core.o
hyn_cst3640_ts-y += hyn_lib/hyn_i2c.o
hyn_cst3640_ts-y += hyn_lib/hyn_ts_ext.o
hyn_cst3640_ts-y += hyn_lib/hyn_fs_node.o
hyn_cst3640_ts-y += hyn_lib/hyn_prox.o
hyn_cst3640_ts-y += hyn_chips/hyn_cst66xx.o
